#pragma config(Sensor, port2,  LightSensor,    sensorVexIQ_ColorHue)
#pragma config(Sensor, port5,  allignSensor,   sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port8,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          RingHolder,    tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor3,          OmniDrive,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RingIntake,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          PivotMotor,    tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// RingmasterJoystick.c

int SPEED = 100;

void loadRings()
{
	string cp = "blue"; //set the "current position" (cp) to blue
	repeat(forever)
  {
// Red Ring ########################################################################
  	if (getColorHue(LightSensor) >= 212) { //if the color is red
  		if (cp == "blue") {
    		moveMotorTarget(RingHolder, 360, 100);
    	}
    	else {
    		if (cp == "green") {
    			moveMotorTarget(RingHolder, -360, -100);
    		}
    	}
  		cp = "red";
  	}
// Green Ring #######################################################################
    	if (getColorHue(LightSensor) <= 127) { // if the color is green
    		if (cp == "blue") {
    			moveMotorTarget(RingHolder, -360, -100);
    		}
    		else {
    			if (cp == "red") {
	    			moveMotorTarget(RingHolder, 360, 100);
    			}
    		}
  		cp = "green";
    	}
// Blue Ring #######################################################################
    	else { // if the color is blue
    		if (cp == "red") {
 		   		moveMotorTarget(RingHolder, -360, -100);
    		}
    		else {
    			if (cp == "green") {
    				moveMotorTarget(RingHolder, 360, 100);
    			}
    		}
  			cp = "blue";
    	}
  	}
  }



task main()
{
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(RingHolder);
	resetMotorEncoder(OmniDrive);
	resetMotorEncoder(RingIntake);
	while(true)
	{
		tankControl(ChD, ChA, 10);

		//If Button "E-Up" is pressed in, we'll set the Pivot motor to run in reverse.
		if(getJoystickValue(BtnEUp) == 1)
		{
			setMotorSpeed(PivotMotor, -127);
		}
		//If the "E-Up" isn't pressed, but "E-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnEDown) == 1)
		{
			setMotorSpeed(PivotMotor, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(PivotMotor, 0);
		}

		//If Button "R-Up" is pressed in, we'll set the Ring Intake motor to run in reverse.
		if(getJoystickValue(BtnRUp) == 1)
		{
			loadRings();
		}
		//If the "R-Up" isn't pressed, but "R-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnRDown) == 1)
		{
			setMotorSpeed(RingIntake, 20);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(RingIntake, 0);
		}

				//If Button "F-Up" is pressed in, we'll set the Ring Holder motor to run in reverse.
		if(getJoystickValue(BtnFUp) == 1)
		{
			setMotorTarget(RingHolder, 360, 127);
		}
		//If the "F-Up" isn't pressed, but "F-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnFDown) == 1)
		{
				setMotorTarget(RingHolder, -360, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
				resetMotorEncoder(RingHolder);
		}

						//If Button "L-Up" is pressed in, we'll set the Omni motor to run in reverse.
		if(getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(OmniDrive, -127);
		}
		//If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnLDown) == 1)
		{
			setMotorSpeed(OmniDrive, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(OmniDrive, 0);
		}

	}
}
