#pragma config(Sensor, port2,  LightSensor,    sensorVexIQ_ColorHue)
#pragma config(Sensor, port5,  allignSensor,   sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port8,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port10, glowyLight,     sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          RingHolder,    tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor3,          OmniDrive,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor4,          RingIntake,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          PivotMotor,    tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor12,         rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// RingmasterJoystick.c

int SPEED = -50;

task loadRings()
{
//	setMotorSpeed(RingIntake, SPEED);
	string cp = "blue"; //set the "current position" (cp) to blue
	repeat(forever)
  {

  	int color = getColorHue(LightSensor); //Sets color variable
  	displayVariableValues(line5, color);
// Red Ring ########################################################################
  	if ((color < 30)) { //if the color is red
  		if (cp == "blue") {
 		   		moveMotorTarget(RingIntake, 310, SPEED);
    			moveMotorTarget(RingHolder, 360, 100);
    			waitUntilMotorStop(RingHolder);
    			moveMotorTarget(RingIntake, 310, SPEED);
    	}
    		if (cp == "green") {
 		   		stopMotor(RingIntake);
    			moveMotorTarget(RingHolder, -360, -100);
    			waitUntilMotorStop(RingHolder);
    			setMotorSpeed(RingIntake, SPEED);
    		}
    	else {
    		if (cp == "red") {
 		   		stopMotor(RingIntake);
    			setMotorSpeed(RingIntake, SPEED);
    		}
    	}
  		cp = "red";
  		displayText(line3, cp);
  		wait(1, seconds);
  	}
// Green Ring #######################################################################
    if ((color < 120) & (color > 50)) { // if the color is green
    	if (cp == "blue") {
 		 		stopMotor(RingIntake);
    		moveMotorTarget(RingHolder, -360, -100);
    		waitUntilMotorStop(RingHolder);
    		setMotorSpeed(RingIntake, SPEED);
    	}
    		if (cp == "red") {
 		 		stopMotor(RingIntake);
    		moveMotorTarget(RingHolder, 360, 100);
    		waitUntilMotorStop(RingHolder);
    		setMotorSpeed(RingIntake, SPEED);
    		}
    	else {
    		if (cp == "green") {
 		   		stopMotor(RingIntake);
    			setMotorSpeed(RingIntake, SPEED);
    		}
    	}
  		cp = "green";
  		displayText(line3, cp);
  		wait(1, seconds);
    }
// Blue Ring #######################################################################
    if ((color > 130) & (color < 200)) { // if the color is blue
    	if (cp == "red") {
 		  	stopMotor(RingIntake);
    		moveMotorTarget(RingHolder, -360, -100);
    		waitUntilMotorStop(RingHolder);
    		setMotorSpeed(RingIntake, SPEED);
    	}
    	if (cp == "green") {
 			  stopMotor(RingIntake);
    		moveMotorTarget(RingHolder, 360, 100);
    		waitUntilMotorStop(RingHolder);
    		setMotorSpeed(RingIntake, SPEED);
    		}
    else {
    		if (cp == "blue") {
 		   		stopMotor(RingIntake);
 		   		setMotorSpeed(RingIntake, SPEED);
    		}
    	}
  		cp = "blue";
  		displayText(line3, cp);
  		wait(1, seconds);
    }
  } //repeatforever
 } //loadrings



task main()
{
	repeat(forever){
		resetMotorEncoder(leftMotor);
	resetMotorEncoder(PivotMotor);
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(RingHolder);
	resetMotorEncoder(OmniDrive);
	resetMotorEncoder(RingIntake);
	resetGyro(gyroSensor);
	displaySensorValues(line1, LightSensor);
		tankControl(ChD, ChA, 10);

if(getJoystickValue(BtnRUp) == 1)
		{
		startTask(loadRings);
		}

			if(getJoystickValue(BtnEUp) == 1)
		{
			setMotorSpeed(OmniDrive, -127);
		}
		//If the "E-Up" isn't pressed, but "E-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnEDown) == 1)
		{
			setMotorSpeed(OmniDrive, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(OmniDrive, 0);
		}
	if(getJoystickValue(BtnLUp) == 1)
		{
			setMotorSpeed(PivotMotor, -127);
		}
		//If the "L-Up" isn't pressed, but "L-Down" is, we'll set the motor to run forward.
		else if(getJoystickValue(BtnLDown) == 1)
		{
			setMotorSpeed(PivotMotor, 127);
		}
		else  //If neither button is pressed, we'll set the motor off.
		{
			setMotorSpeed(PivotMotor, 0);
		}
	}
}
